#!/bin/sh

setxkbmap -layout de
xrandr --output eDP1 --off --output HDMI1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output VIRTUAL1 --off
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom &
polybar &
sxhkd &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc monitor HDMI1 -d α β γ δ ε ζ η θ ι κ
bspc monitor eDP1
bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color '#06a284'
bspc config normal_border_color '#191d22'
bspc config active_border_color '#ffffff'
bspc config presel_feedback_color '#06a284'
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
