format = """
$pytohn$directory$git_branch$character
"""

add_newline = false

[python]
format = '[(\($virtualenv\) )](bold yellow)'

[username]
show_always = true
format = "[$user](bold red)"

[hostname]
ssh_only = false
format = "[@$hostname](blue)"

[directory]
format = "[$path](bold blue) "

[git_branch]
format = '[\($branch\)](purple) '

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](blue)"
